name: learn-github-actions

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout source repo
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: pip install black

    - name: Run black --check .
      run: black --check .

    - name: checks if fail
      if: failure()
      run: |
        black .
        git config --global user.name 'Github Action'
        git config --global user.email 'action@github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GH_ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout $GITHUB_HEAD_REF
        git commit -am "fixup: Format Python code with Black"
        git push
