name: github-actions-testing

on: [push, pull_request]

jobs:
  format:

    runs-on: ubuntu-latest
    name: Formatting

    steps:
    - name: checkout source repo
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        python -m pip install pipenv
        python -m pipenv sync --dev

    - name: format python imports by isort
      run: pipenv run isort .

    - name: format python code by black
      run: pipenv run black .

    - name: git adds, commits, and pushes
      continue-on-error: true
      run: |
        git config --global user.name 'Github Action'
        git config --global user.email 'action@github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GH_ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout $GITHUB_HEAD_REF
        git commit -am "fixup: Format Python code with Black and Isort"
        git push


  linting:

    needs: format
    runs-on: ubuntu-latest
    name: Linting

    steps:
    - name: checkout source repo
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        python -m pip install pipenv
        python -m pipenv sync --dev

    - name: lints the code
      run: pipenv run flake8 .
