name: learn-github-actions
on: [push, pull_request]
jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2

    - name: Install Black
      run: pip install black

    - name: Run black --check .
      run: black --check .

    - name: If needed, commit black changes to the pull request
      if: failure()
      run: |
        black .

    - name: commit changes
        git config --global user.name 'Github Action'
        git config --global user.email 'action@github.com'
        git commit -am 'fixup: Format Python code with Black'
        git push

    - name: push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GH_ACCESS_TOKEN }}
        branch: ${{ github.ref }}
